const MovieDetailsActionTypes = {
    FETCH_MOVIE_DETAILS: 'FETCH_MOVIE_DETAILS',
    FETCH_MOVIE_DETAILS_START: 'FETCH_MOVIE_DETAILS_START',
    FETCH_MOVIE_DETAILS_SUCCESS: 'FETCH_MOVIE_DETAILS_SUCCESS',
    FETCH_MOVIE_DETAILS_FAILURE: 'FETCH_MOVIE_DETAILS_FAILURE',
}

export default MovieDetailsActionTypes;