const HeaderActionTypes = {
    SEARCH_INPUT_CHANGE: 'SEARCH_INPUT_CHANGE',
    CHANGE_SEARCH_TEXT: 'CHANGE_SEARCH_TEXT',
    UPDATE_MOVIE_LIST: 'UPDATE_MOVIE_LIST',

    TOGGLE_THEME_CHECKBOX: 'TOGGLE_THEME_CHECKBOX'
}

export default HeaderActionTypes;